export const DEBUG = window.location.host.includes('localhost');
export const BATTLE_CHAR_WIDTH = 96;
export const BATTLE_CHAR_HEIGHT = 96;
export const ACTION_POINT_WIDTH = 16;
export const ACTION_POINT_HEIGHT = 16;
//export const aspectRatio = 16 / 9;
export const GAME_H = 640;
export const GAME_W = 800;
export const GAME_ZOOM = 1.25;
export const PLAYER_WORLD_SPEED = 150;
export const PLAYER_RUN_WORLD_SPEED = 250;
//# sourceMappingURL=constants.js.map